language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly
# - pypy still no pypy 2.6

install:
  - make install

script:
  - make lint
  - make check

after_success: coveralls

sudo: false
